export const current_services = {
  "Other service": "",
  "New pan card": "250",
  "Correction pan card": "250",
  "E-pan card download with color print": "80",
  "Pan card reprint": "150",
  "Pan card Aadhaar link": "40",
  "Aadhaar name, address, DOB, gender correction": "100",
  "Aadhaar reprint": "100",
  "E-Aadhaar download with color print": "60",
  "New ration card": "150",
  "Address change in ration card": "80",
  "Name remove in ration card": "80",
  "Add name in ration card": "80",
  "Change family head in ration card": "80",
  "New passport": "1800",
  "Renewal passport": "1800",
  "Correction passport": "1800",
  "Child passport": "1300",
  "Bus ticket booking (booking + charges)": "",
  "Train ticket booking (booking + charges)": "",
  "Two-wheeler insurance": "100",
  "Corp insurance": "100",
  "Chitta / A-register / FMB": "20",
  "Adangal paper": "5",
  "EC (Villanga chantru) certificate generate rate 50 + additional paper 5/sheet": "50",
  "EB bill": "10",
  "All exam application fees": "150",
  "New voter ID": "80",
  "Correction voter ID": "80",
  "Employment new": "80",
  "Renewal": "40",
  "Birth / death certificate register": "120",
  "Block and color birth / death print": "20",
  "Community certificate": "60",
  "Income certificate": "60",
  "Native certificate": "60",
  "First graduate": "60",
  "Small farmer": "60",
  "No male child": "60",
  "OBC certificate": "60",
  "Inter caste marriage": "60",
  "Deceased woman certificate": "60",
  "Legal heir certificate": "60",
  "Widow certificate": "60",
  "Unmarried certificate": "60",
  "Unemployment certificate": "60",
  "Solvency certificate": "60",
  "Patta transfer": "120",
  "Marriage assistant certificate": "60",
  "Two female child fund certificate": "60",
  "Money transfer": "",
  "Cash withdrawal": "",
  "MSME registration": "150",
  "PM Kisan registration": "120",
  "PM Kisan correction": "120",
  "Computer jathagam (basic 30 + additional paper 5)": "60",
  "EPFO claiming": "80",
  "EPFO any correction": "80",
  "Pensioner life certificate": "50",
  "RTE act": "120",
  "Lamination ID card": "10",
  "Lamination A4 paper": "40",
  "Lamination legal paper": "50",
  "Xerox per page": "2",
  "Print per page (first paper 5)": "5",
  "Email access": "10",
  "Scan copy / 1 page": "5",
  "Flight ticket": "",
  "Xerox back to back": "3",
  "TNEB new application": "150",
  "TNUWWB card pension registration": "",
  "Loan repayment": ""
};